# Generated by Django 4.2.7 on 2026-06-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت پرداخت'),
        ),
    ]
