# Generated by Django 4.2.7 on 2026-06-23 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0002_invoice_accounting_invoice_number_and_more'),
        ('customers', '0001_initial'),
        ('payments', '0002_payment_payment_date_payment_payment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('account_number', models.CharField(max_length=50, verbose_name='شماره حساب')),
                ('card_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره کارت')),
                ('shaba_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره شبا')),
                ('account_holder', models.CharField(max_length=200, verbose_name='صاحب حساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام'),
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('wallet', 'پرداخت از کیف پول'), ('online', 'پرداخت آنلاین'), ('card_to_card', 'کارت به کارت'), ('bank_transfer', 'حواله بانکی'), ('cheque', 'ثبت چک')], max_length=20, verbose_name='روش پرداخت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ')),
                ('confirmation_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('payment_time', models.TimeField(blank=True, null=True, verbose_name='ساعت پرداخت')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='payments/receipts/', verbose_name='تصویر رسید')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('awaiting_approval', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('accounting_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره در حسابداری')),
                ('sent_to_accounting', models.BooleanField(default=False, verbose_name='ارسال به حسابداری')),
                ('sent_to_accounting_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال به حسابداری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.bankaccount', verbose_name='حساب مقصد')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_invoice_payments', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payments', to='customers.customer', verbose_name='مشتری')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'پرداخت فاکتور',
                'verbose_name_plural': 'پرداخت\u200cهای فاکتور',
                'ordering': ['-created_at'],
            },
        ),
    ]
