# Generated by Django 4.2.7 on 2026-06-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_bankaccount_alter_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_category',
            field=models.CharField(choices=[('wallet', 'شارژ کیف پول'), ('invoice', 'پرداخت فاکتور'), ('debt', 'پرداخت بدهی')], default='wallet', max_length=20, verbose_name='دسته\u200cبندی پرداخت'),
        ),
    ]
