# Generated by Django 4.2.7 on 2026-06-27 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_payment_payment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='accounting_document_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('online', 'آنلاین'), ('wallet', 'کیف پول'), ('cash', 'نقدی'), ('cheque', 'چک'), ('pos', 'کارتخوان'), ('transfer', 'انتقال بانکی')], default='online', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='needs_approval',
            field=models.BooleanField(default=False),
        ),
    ]
