# Generated by Django 4.2.7 on 2026-07-22 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_accounting_document_no_payment_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
        ),
    ]
