# Generated by Django 4.2.7 on 2026-06-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اسلایدر')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='زیرنویس')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='تصویر اسلایدر')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='لینک دکمه')),
                ('link_text', models.CharField(blank=True, default='مشاهده', max_length=100, null=True, verbose_name='متن دکمه')),
                ('position', models.CharField(choices=[('hero', 'اسلایدر اصلی (هیرو)'), ('banner', 'بنر تبلیغاتی')], default='hero', max_length=20, verbose_name='موقعیت')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
                'ordering': ['position', 'order', 'created_at'],
            },
        ),
    ]
