# Generated by Django 4.2.7 on 2026-06-17 11:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('view_customers', 'مشاهده مشتریان'), ('add_customers', 'افزودن مشتری'), ('edit_customers', 'ویرایش مشتریان'), ('delete_customers', 'حذف مشتریان'), ('view_products', 'مشاهده محصولات'), ('add_products', 'افزودن محصول'), ('edit_products', 'ویرایش محصولات'), ('delete_products', 'حذف محصولات'), ('import_products', 'وارد کردن انبوه محصولات'), ('view_invoices', 'مشاهده فاکتورها'), ('add_invoices', 'افزودن فاکتور'), ('edit_invoices', 'ویرایش فاکتورها'), ('delete_invoices', 'حذف فاکتورها'), ('confirm_invoices', 'تایید فاکتورها'), ('view_payments', 'مشاهده پرداخت\u200cها'), ('add_payments', 'افزودن پرداخت'), ('edit_payments', 'ویرایش پرداخت\u200cها'), ('delete_payments', 'حذف پرداخت\u200cها'), ('confirm_payments', 'تایید پرداخت\u200cها'), ('view_employees', 'مشاهده کارمندان'), ('add_employees', 'افزودن کارمند'), ('edit_employees', 'ویرایش کارمندان'), ('delete_employees', 'حذف کارمندان'), ('manage_permissions', 'مدیریت دسترسی\u200cها'), ('view_reports', 'مشاهده گزارشات'), ('export_reports', 'خروجی گرفتن از گزارشات'), ('sync_prices', 'همگام\u200cسازی قیمت\u200cها'), ('view_brands', 'مشاهده برندها'), ('edit_brands', 'ویرایش برندها'), ('view_categories', 'مشاهده دسته\u200cبندی'), ('edit_categories', 'ویرایش دسته\u200cبندی'), ('view_cars', 'مشاهده خودروها'), ('edit_cars', 'ویرایش خودروها')], max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('module', models.CharField(blank=True, max_length=50, null=True, verbose_name='ماژول')),
            ],
            options={
                'verbose_name': 'دسترسی کارمند',
                'verbose_name_plural': 'دسترسی\u200cهای کارمندان',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'کد ملی باید 10 رقم باشد')], verbose_name='کد ملی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('position', models.CharField(max_length=100, verbose_name='سمت')),
                ('access_customers', models.BooleanField(default=False, verbose_name='دسترسی به مدیریت مشتریان')),
                ('access_products', models.BooleanField(default=False, verbose_name='دسترسی به مدیریت محصولات')),
                ('access_invoices', models.BooleanField(default=False, verbose_name='دسترسی به مدیریت فاکتورها')),
                ('access_payments', models.BooleanField(default=False, verbose_name='دسترسی به مدیریت پرداخت\u200cها')),
                ('access_employees', models.BooleanField(default=False, verbose_name='دسترسی به مدیریت کارمندان')),
                ('access_reports', models.BooleanField(default=False, verbose_name='دسترسی به گزارشات')),
                ('access_sync', models.BooleanField(default=False, verbose_name='دسترسی به همگام\u200cسازی قیمت\u200cها')),
                ('access_brands_categories', models.BooleanField(default=False, verbose_name='دسترسی به مدیریت برندها و دسته\u200cبندی')),
                ('access_blog', models.BooleanField(default=False, verbose_name='دسترسی به مدیریت محتوا (بلاگ)')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('hired_date', models.DateField(auto_now_add=True, verbose_name='تاریخ استخدام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
            },
        ),
    ]
