# Generated by Django 4.2.7 on 2026-06-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='access_comments',
            field=models.BooleanField(default=False, verbose_name='دسترسی به مدیریت نظرات'),
        ),
    ]
