# Generated by Django 4.2.7 on 2026-06-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_access_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='access_website',
            field=models.BooleanField(default=False, verbose_name='دسترسی به مدیریت وبسایت'),
        ),
    ]
