# Generated by Django 4.2.7 on 2026-07-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_access_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepermission',
            name='name',
            field=models.CharField(choices=[('view_customers', 'مشاهده مشتریان'), ('add_customers', 'افزودن مشتری'), ('edit_customers', 'ویرایش مشتریان'), ('delete_customers', 'حذف مشتریان'), ('view_products', 'مشاهده محصولات'), ('add_products', 'افزودن محصول'), ('edit_products', 'ویرایش محصولات'), ('delete_products', 'حذف محصولات'), ('import_products', 'وارد کردن انبوه محصولات'), ('view_invoices', 'مشاهده فاکتورها'), ('add_invoices', 'افزودن فاکتور'), ('edit_invoices', 'ویرایش فاکتورها'), ('delete_invoices', 'حذف فاکتورها'), ('confirm_invoices', 'تایید فاکتورها'), ('view_payments', 'مشاهده پرداخت\u200cها'), ('add_payments', 'افزودن پرداخت'), ('edit_payments', 'ویرایش پرداخت\u200cها'), ('delete_payments', 'حذف پرداخت\u200cها'), ('confirm_payments', 'تایید پرداخت\u200cها'), ('view_employees', 'مشاهده کارمندان'), ('add_employees', 'افزودن کارمند'), ('edit_employees', 'ویرایش کارمندان'), ('delete_employees', 'حذف کارمندان'), ('manage_permissions', 'مدیریت دسترسی\u200cها'), ('view_reports', 'مشاهده گزارشات'), ('export_reports', 'خروجی گرفتن از گزارشات'), ('sync_prices', 'همگام\u200cسازی اطلاعات با  سیستم حسابداری'), ('view_brands', 'مشاهده برندها'), ('edit_brands', 'ویرایش برندها'), ('view_categories', 'مشاهده دسته\u200cبندی'), ('edit_categories', 'ویرایش دسته\u200cبندی'), ('view_cars', 'مشاهده خودروها'), ('edit_cars', 'ویرایش خودروها')], max_length=50, unique=True),
        ),
    ]
