# Generated by Django 4.2.7 on 2026-06-23 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_slug'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='accounting_invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره فاکتور در سیستم حسابداری'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_payment_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین تلاش برای پرداخت'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_attempts',
            field=models.IntegerField(default=0, verbose_name='تعداد تلاش\u200cهای پرداخت'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cهای پرداخت'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_to_accounting',
            field=models.BooleanField(default=False, verbose_name='ارسال به سیستم حسابداری'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_to_accounting_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال به سیستم حسابداری'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.invoice', verbose_name='فاکتور'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='points_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='امتیاز کسب شده'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='invoicestatus',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='کد وضعیت'),
        ),
        migrations.AlterField(
            model_name='invoicestatus',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='وضعیت نهایی'),
        ),
        migrations.AlterField(
            model_name='invoicestatus',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام وضعیت'),
        ),
    ]
