# Generated by Django 4.2.7 on 2026-06-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_accounting_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='accounting_invoice_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره فاکتور در حسابداری'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'پرداخت نشده'), ('paid', 'پرداخت شده'), ('partial', 'جزئی')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.invoicestatus'),
        ),
    ]
