# Generated by Django 4.2.7 on 2026-07-04 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_product_code'),
        ('invoices', '0003_invoice_accounting_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد محصول در نیکان'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام محصول در نیکان'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول'),
        ),
    ]
