# Generated by Django 4.2.7 on 2026-07-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoiceitem_product_code_invoiceitem_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product_code',
            field=models.CharField(default='0', max_length=50, verbose_name='کد محصول در نیکان'),
        ),
    ]
