# Generated by Django 4.2.7 on 2026-07-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='manual_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='تخفیف دستی (ادمین)'),
        ),
    ]
