# Generated by Django 4.2.7 on 2026-06-17 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'کد ملی باید 10 رقم باشد')], verbose_name='کد ملی')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'شماره تلفن باید با 09 شروع شود')], verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شهر')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='خیابان')),
                ('address', models.TextField(blank=True, verbose_name='آدرس دقیق')),
                ('invitation_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد معرف')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('viewed', 'مشاهده شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='مشاهده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ مشاهده')),
            ],
            options={
                'verbose_name': 'درخواست ثبت\u200cنام',
                'verbose_name_plural': 'درخواست\u200cهای ثبت\u200cنام',
                'ordering': ['-created_at'],
            },
        ),
    ]
