# Generated by Django 4.2.7 on 2026-06-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
    ]
