# Generated by Django 4.2.7 on 2026-06-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_registrationrequest_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'مدیر ارشد'), ('employee', 'کارمند'), ('customer', 'مشتری'), ('pending', 'در انتظار تایید')], default='pending', max_length=10, verbose_name='نوع کاربر'),
        ),
    ]
