# Generated by Django 4.2.7 on 2026-06-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'دسته بلاگ',
                'verbose_name_plural': 'دسته\u200cهای بلاگ',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(upload_to='blog/', verbose_name='تصویر شاخص')),
                ('summary', models.TextField(max_length=300, verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='متن کامل')),
                ('author', models.CharField(default='مدیریت', max_length=100, verbose_name='نویسنده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.blogcategory', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'پست بلاگ',
                'verbose_name_plural': 'پست\u200cهای بلاگ',
                'ordering': ['-created_at'],
            },
        ),
    ]
