# Generated by Django 4.2.7 on 2026-07-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='setting_type',
            field=models.CharField(choices=[('about', 'تنظیمات درباره ما'), ('hero', 'تنظیمات هیرو')], default='about', max_length=20, verbose_name='نوع'),
        ),
    ]
