# Generated by Django 4.2.7 on 2026-07-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_delete_teammember_alter_sitesetting_setting_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={},
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='setting_type',
            field=models.CharField(choices=[('about', 'درباره ما'), ('hero', 'هیرو')], default='about', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
