# Generated by Django 4.2.7 on 2026-06-17 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_credit', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='اعتبار حداکثر')),
                ('credit', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='اعتبار فعلی')),
                ('wallet', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='موجودی کیف پول')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='امتیاز کل')),
                ('used_points', models.PositiveIntegerField(default=0, verbose_name='امتیاز استفاده شده')),
                ('total_purchases', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='کل خرید')),
                ('total_payments', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='کل پرداخت\u200cها')),
                ('invitations_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دعوت\u200cشدگان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='CustomerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام سطح')),
                ('min_credit', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='حداقل اعتبار مورد نیاز')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='اولویت')),
            ],
            options={
                'verbose_name': 'سطح مشتری',
                'verbose_name_plural': 'سطوح مشتریان',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='تعداد امتیاز')),
                ('reason', models.CharField(max_length=200, verbose_name='دلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_history', to='customers.customer')),
            ],
            options={
                'verbose_name': 'تاریخچه امتیاز',
                'verbose_name_plural': 'تاریخچه امتیازات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.customerlevel', verbose_name='سطح مشتری'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
