# Generated by Django 4.2.7 on 2026-06-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد مشتری (نیکان)'),
        ),
    ]
