# Generated by Django 4.2.7 on 2026-06-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nikan_customer_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد مشتری (نیکان)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='nikan_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ همگام\u200cسازی'),
        ),
        migrations.AddField(
            model_name='customer',
            name='nikan_sync_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش\u200cها'),
        ),
        migrations.AddField(
            model_name='customer',
            name='nikan_sync_error',
            field=models.TextField(blank=True, null=True, verbose_name='خطای همگام\u200cسازی'),
        ),
        migrations.AddField(
            model_name='customer',
            name='nikan_sync_status',
            field=models.CharField(choices=[('pending', 'در انتظار همگام\u200cسازی'), ('synced', 'همگام\u200cسازی شده'), ('failed', 'همگام\u200cسازی ناموفق')], default='pending', max_length=20, verbose_name='وضعیت همگام\u200cسازی با نیکان'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد مشتری (سایت)'),
        ),
    ]
