# Generated by Django 4.2.7 on 2026-07-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_nikan_customer_code_customer_nikan_sync_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wallet',
        ),
    ]
