# Generated by Django 4.2.7 on 2026-07-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='debt_before_1404_02',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='بدهی قبل از ۱۴۰۴/۰۲'),
        ),
    ]
