# Generated by Django 4.2.7 on 2026-06-26 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_productimage_thumb'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('customers', 'مشتریان'), ('products', 'محصولات'), ('invoices', 'فاکتورها'), ('payments', 'پرداخت\u200cها')], max_length=20, verbose_name='نوع همگام\u200cسازی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('last_synced_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='آخرین کد همگام\u200cسازی')),
                ('new_items_count', models.PositiveIntegerField(default=0, verbose_name='تعداد آیتم\u200cهای جدید')),
                ('failed_items_count', models.PositiveIntegerField(default=0, verbose_name='تعداد آیتم\u200cهای ناموفق')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
            ],
            options={
                'verbose_name': 'لاگ همگام\u200cسازی',
                'verbose_name_plural': 'لاگ\u200cهای همگام\u200cسازی',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountingProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_code', models.CharField(max_length=50, unique=True, verbose_name='کد محصول در حسابداری')),
                ('technical_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره فنی')),
                ('last_sync_at', models.DateTimeField(auto_now=True, verbose_name='آخرین همگام\u200cسازی')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_mapping', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نگاشت محصول حسابداری',
                'verbose_name_plural': 'نگاشت\u200cهای محصول حسابداری',
            },
        ),
        migrations.CreateModel(
            name='AccountingCustomerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_code', models.CharField(max_length=50, unique=True, verbose_name='کد مشتری در حسابداری')),
                ('last_sync_at', models.DateTimeField(auto_now=True, verbose_name='آخرین همگام\u200cسازی')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_mapping', to='customers.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'نگاشت مشتری حسابداری',
                'verbose_name_plural': 'نگاشت\u200cهای مشتری حسابداری',
            },
        ),
    ]
