# Generated by Django 4.2.7 on 2026-06-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('payment_failed', 'خطا در ثبت پرداخت'), ('invoice_failed', 'خطا در ثبت فاکتور'), ('sync_failed', 'خطا در همگام\u200cسازی')], max_length=20, verbose_name='نوع خطا')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('related_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه مرتبط')),
                ('related_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدل مرتبط')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خواندن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نوتیفیکیشن حسابداری',
                'verbose_name_plural': 'نوتیفیکیشن\u200cهای حسابداری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='accountingsynclog',
            name='sync_type',
            field=models.CharField(choices=[('customers', 'مشتریان'), ('products', 'محصولات'), ('invoices', 'فاکتورها'), ('payments', 'پرداخت\u200cها'), ('full', 'همگام\u200cسازی کامل')], max_length=20, verbose_name='نوع همگام\u200cسازی'),
        ),
    ]
