# Generated by Django 4.2.7 on 2026-06-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountingnotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_type', models.CharField(choices=[('customer', 'شماره مشتری'), ('product', 'شماره محصول'), ('invoice', 'شماره فاکتور'), ('payment', 'شماره پرداخت')], max_length=20, unique=True, verbose_name='نوع شمارنده')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='آخرین شماره')),
                ('last_sync_at', models.DateTimeField(auto_now=True, verbose_name='آخرین همگام\u200cسازی')),
            ],
            options={
                'verbose_name': 'شمارنده حسابداری',
                'verbose_name_plural': 'شمارنده\u200cهای حسابداری',
            },
        ),
    ]
