# Generated by Django 4.2.7 on 2026-06-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountingcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_type', models.CharField(choices=[('customer', 'مشتری'), ('product', 'محصول'), ('invoice', 'فاکتور'), ('payment', 'پرداخت')], max_length=20, verbose_name='نوع')),
                ('object_id', models.PositiveIntegerField(verbose_name='شناسه شیء')),
                ('data', models.JSONField(default=dict, verbose_name='داده\u200cهای درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پردازش')),
            ],
            options={
                'verbose_name': 'آیتم صف همگام\u200cسازی',
                'verbose_name_plural': 'آیتم\u200cهای صف همگام\u200cسازی',
                'ordering': ['-created_at'],
            },
        ),
    ]
