# Generated by Django 4.2.7 on 2026-06-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام خودرو')),
                ('model', models.CharField(blank=True, max_length=20, verbose_name='سال تولید')),
            ],
            options={
                'verbose_name': 'خودرو',
                'verbose_name_plural': 'خودروها',
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام برند خودرو')),
                ('country', models.CharField(max_length=100, verbose_name='کشور سازنده')),
            ],
            options={
                'verbose_name': 'برند خودرو',
                'verbose_name_plural': 'برندهای خودرو',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته اصلی')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دسته اصلی',
                'verbose_name_plural': 'دسته\u200cهای اصلی',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('product_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره محصول اصلی')),
                ('alt_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره جایگزین')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت (ریال)')),
                ('off_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='قیمت تخفیف\u200cخورده')),
                ('left_in_stock', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='تخصص/نوع')),
                ('point_of_buy', models.PositiveIntegerField(default=0, verbose_name='امتیاز خرید محصول')),
                ('sold_number', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش رفته')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='توضیح مختصر')),
                ('full_description', models.TextField(blank=True, verbose_name='توضیحات کامل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='محصول ویژه')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-sold_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام برند')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('country', models.CharField(max_length=100, verbose_name='کشور')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'برند محصول',
                'verbose_name_plural': 'برندهای محصول',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام زیردسته')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.maincategory', verbose_name='دسته اصلی')),
            ],
            options={
                'verbose_name': 'زیردسته',
                'verbose_name_plural': 'زیردسته\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر')),
                ('is_main', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
                'ordering': ['order', '-is_main'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productbrand', verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.maincategory', verbose_name='دسته اصلی'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.subcategory', verbose_name='زیردسته'),
        ),
        migrations.AddField(
            model_name='product',
            name='suitable_car',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.car', verbose_name='خودروی مناسب'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='products.carbrand', verbose_name='برند خودرو'),
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام جایگزین')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نام جایگزین محصول',
                'verbose_name_plural': 'نام\u200cهای جایگزین محصولات',
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('car_brand', 'name', 'model')},
        ),
    ]
