# Generated by Django 4.2.7 on 2026-06-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbs/', verbose_name='تصویر کوچک'),
        ),
    ]
