# Generated by Django 4.2.7 on 2026-06-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد محصول (نیکان)'),
        ),
    ]
